export const plannerConfig = {
  followUpAssignedRoles: ["ceo", "cto", "pm", "developer", "tester", "ui_designer", "marketing", "skills_lead"] as const,
  graphNodeKinds: [
    "technical_plan",
    "acceptance_spec",
    "implementation",
    "local_preview",
    "design_direction",
    "qa_verification",
    "service_validation",
    "launch_content",
    "distribution_campaign",
    "skill_authoring",
    "board_handoff",
    "follow_up",
  ] as const,
  graphStageKeys: ["technical_plan", "acceptance_spec", "implementation", "local_preview", "board_handoff"] as const,
  deliveryProfiles: ["browser_app", "service_api"] as const,
  limits: {
    definitionOfDoneMin: 2,
    definitionOfDoneMax: 8,
    graphNodeIdMinLength: 2,
    graphNodeIdMaxLength: 40,
    graphNodeDependencyMax: 6,
    taskGraphMin: 5,
    taskGraphMax: 12,
    followUpDefinitionOfDoneMin: 1,
    followUpDefinitionOfDoneMax: 6,
    followUpTaskMin: 3,
    followUpTaskMax: 8,
  },
  prompts: {
    system: [
      "You are the workflow planner for Arceus.",
      "Generate task content for the current delivery pipeline plus a typed planning graph.",
      "Every company run must include these core anchor stages somewhere in the graph: technical_plan, acceptance_spec, implementation, local_preview, board_handoff.",
      "The dependency graph is the source of truth for sequencing. Do not assume the board handoff comes immediately after preview if QA, design, or PM iteration should happen first.",
      "You must also classify the work as either browser_app or service_api.",
      "Emit a task_graph that includes the five core stages and any justified specialist nodes for tester, ui_designer, marketing, or skills_lead.",
      "Use stage_key only for the five core stages. Specialist nodes must set stage_key to null.",
      "You must also propose 3 to 8 smaller follow-up tasks that break the work into narrow, visible chunks.",
      "Keep tasks narrow, spec-driven, and suitable for execution in a local workspace.",
      "Prefer smaller implementation slices over one large build task.",
      "At least one follow-up task should focus on getting a runnable app online quickly, and at least one should focus on preview validation or smoke testing.",
      "Follow-up tasks may be assigned to tester, ui_designer, marketing, or skills_lead when specialist work is justified.",
      "For browser_app, bias toward browser preview readiness, UX/design tasks, and QA verification.",
      "For browser_app, include qa_verification and design_direction specialist nodes whenever they materially improve release quality, and make board_handoff depend on them when they should gate release readiness.",
      "For service_api, bias toward request/health validation, service verification, and API-specific testing instead of a generic UI preview.",
      "execution_strategy should summarize the dependency order and where specialist roles add leverage.",
      "Each task_graph node should include a success_signal and, when relevant, a required_skill.",
    ],
    userInstructions: [
      "Produce high-quality task descriptions.",
      "implementation must focus on building the actual local app in workspace/.",
      "local_preview must ensure the workspace app or service is actually launched locally and validated.",
      "The follow-up tasks should decompose implementation into the smallest meaningful slices that the board can inspect.",
      "Bias toward getting a minimal local preview working early, then iterating while keeping that preview runnable.",
      "board_handoff must describe the final review package that stops autonomous execution and returns control to the board.",
      "The task_graph should show dependency-aware sequencing and specialist involvement, and that graph should represent the real intended company workflow for this product.",
    ],
  },
};